units:
	@xctool -project ./Mabataki.xcodeproj -scheme "Mabataki" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=9.3,name=iPhone 6" test

bootstrap:
	carthage bootstrap --platform iOS

update:
	carthage update --platform iOS
